// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

type TokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGenerator) EXPECT() *TokenGenerator_Expecter {
	return &TokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type TokenGenerator
func (_mock *TokenGenerator) Generate(userID int64, email string) (string, error) {
	ret := _mock.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (string, error)); ok {
		return returnFunc(userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = returnFunc(userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID int64
//   - email string
func (_e *TokenGenerator_Expecter) Generate(userID interface{}, email interface{}) *TokenGenerator_Generate_Call {
	return &TokenGenerator_Generate_Call{Call: _e.mock.On("Generate", userID, email)}
}

func (_c *TokenGenerator_Generate_Call) Run(run func(userID int64, email string)) *TokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenGenerator_Generate_Call) Return(s string, err error) *TokenGenerator_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenGenerator_Generate_Call) RunAndReturn(run func(userID int64, email string) (string, error)) *TokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
