// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/human9001/teams/internal/application/service/user"
	user0 "github.com/human9001/teams/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

type IUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserService) EXPECT() *IUserService_Expecter {
	return &IUserService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type IUserService
func (_mock *IUserService) Login(ctx context.Context, in user.LoginInput) (*user.LoginResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.LoginInput) (*user.LoginResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.LoginInput) *user.LoginResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.LoginInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type IUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.LoginInput
func (_e *IUserService_Expecter) Login(ctx interface{}, in interface{}) *IUserService_Login_Call {
	return &IUserService_Login_Call{Call: _e.mock.On("Login", ctx, in)}
}

func (_c *IUserService_Login_Call) Run(run func(ctx context.Context, in user.LoginInput)) *IUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.LoginInput
		if args[1] != nil {
			arg1 = args[1].(user.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_Login_Call) Return(loginResult *user.LoginResult, err error) *IUserService_Login_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *IUserService_Login_Call) RunAndReturn(run func(ctx context.Context, in user.LoginInput) (*user.LoginResult, error)) *IUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type IUserService
func (_mock *IUserService) Register(ctx context.Context, in user.RegisterInput) (*user0.User, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.RegisterInput) (*user0.User, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.RegisterInput) *user0.User); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user0.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.RegisterInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in user.RegisterInput
func (_e *IUserService_Expecter) Register(ctx interface{}, in interface{}) *IUserService_Register_Call {
	return &IUserService_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *IUserService_Register_Call) Run(run func(ctx context.Context, in user.RegisterInput)) *IUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(user.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_Register_Call) Return(user1 *user0.User, err error) *IUserService_Register_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *IUserService_Register_Call) RunAndReturn(run func(ctx context.Context, in user.RegisterInput) (*user0.User, error)) *IUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
