// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/human9001/teams/internal/application/service/history/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewITaskHistoryService creates a new instance of ITaskHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITaskHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITaskHistoryService {
	mock := &ITaskHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITaskHistoryService is an autogenerated mock type for the ITaskHistoryService type
type ITaskHistoryService struct {
	mock.Mock
}

type ITaskHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *ITaskHistoryService) EXPECT() *ITaskHistoryService_Expecter {
	return &ITaskHistoryService_Expecter{mock: &_m.Mock}
}

// GetTaskHistory provides a mock function for the type ITaskHistoryService
func (_mock *ITaskHistoryService) GetTaskHistory(ctx context.Context, taskID int64) (dto.ListHistoryResult, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskHistory")
	}

	var r0 dto.ListHistoryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (dto.ListHistoryResult, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) dto.ListHistoryResult); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(dto.ListHistoryResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITaskHistoryService_GetTaskHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskHistory'
type ITaskHistoryService_GetTaskHistory_Call struct {
	*mock.Call
}

// GetTaskHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *ITaskHistoryService_Expecter) GetTaskHistory(ctx interface{}, taskID interface{}) *ITaskHistoryService_GetTaskHistory_Call {
	return &ITaskHistoryService_GetTaskHistory_Call{Call: _e.mock.On("GetTaskHistory", ctx, taskID)}
}

func (_c *ITaskHistoryService_GetTaskHistory_Call) Run(run func(ctx context.Context, taskID int64)) *ITaskHistoryService_GetTaskHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITaskHistoryService_GetTaskHistory_Call) Return(listHistoryResult dto.ListHistoryResult, err error) *ITaskHistoryService_GetTaskHistory_Call {
	_c.Call.Return(listHistoryResult, err)
	return _c
}

func (_c *ITaskHistoryService_GetTaskHistory_Call) RunAndReturn(run func(ctx context.Context, taskID int64) (dto.ListHistoryResult, error)) *ITaskHistoryService_GetTaskHistory_Call {
	_c.Call.Return(run)
	return _c
}
