// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/human9001/teams/internal/domain/team"
	mock "github.com/stretchr/testify/mock"
)

// NewITeamService creates a new instance of ITeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITeamService {
	mock := &ITeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITeamService is an autogenerated mock type for the ITeamService type
type ITeamService struct {
	mock.Mock
}

type ITeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *ITeamService) EXPECT() *ITeamService_Expecter {
	return &ITeamService_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function for the type ITeamService
func (_mock *ITeamService) CreateTeam(ctx context.Context, name string, ownerID int64) (*team.Team, error) {
	ret := _mock.Called(ctx, name, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *team.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (*team.Team, error)); ok {
		return returnFunc(ctx, name, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) *team.Team); ok {
		r0 = returnFunc(ctx, name, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, name, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITeamService_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type ITeamService_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ownerID int64
func (_e *ITeamService_Expecter) CreateTeam(ctx interface{}, name interface{}, ownerID interface{}) *ITeamService_CreateTeam_Call {
	return &ITeamService_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, name, ownerID)}
}

func (_c *ITeamService_CreateTeam_Call) Run(run func(ctx context.Context, name string, ownerID int64)) *ITeamService_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ITeamService_CreateTeam_Call) Return(team1 *team.Team, err error) *ITeamService_CreateTeam_Call {
	_c.Call.Return(team1, err)
	return _c
}

func (_c *ITeamService_CreateTeam_Call) RunAndReturn(run func(ctx context.Context, name string, ownerID int64) (*team.Team, error)) *ITeamService_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function for the type ITeamService
func (_mock *ITeamService) ListTeams(ctx context.Context, ownerID int64) ([]team.Team, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []team.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]team.Team, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []team.Team); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]team.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITeamService_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type ITeamService_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *ITeamService_Expecter) ListTeams(ctx interface{}, ownerID interface{}) *ITeamService_ListTeams_Call {
	return &ITeamService_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx, ownerID)}
}

func (_c *ITeamService_ListTeams_Call) Run(run func(ctx context.Context, ownerID int64)) *ITeamService_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITeamService_ListTeams_Call) Return(teams []team.Team, err error) *ITeamService_ListTeams_Call {
	_c.Call.Return(teams, err)
	return _c
}

func (_c *ITeamService_ListTeams_Call) RunAndReturn(run func(ctx context.Context, ownerID int64) ([]team.Team, error)) *ITeamService_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}
