// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/human9001/teams/internal/application/service/comment/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewICommentService creates a new instance of ICommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommentService {
	mock := &ICommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ICommentService is an autogenerated mock type for the ICommentService type
type ICommentService struct {
	mock.Mock
}

type ICommentService_Expecter struct {
	mock *mock.Mock
}

func (_m *ICommentService) EXPECT() *ICommentService_Expecter {
	return &ICommentService_Expecter{mock: &_m.Mock}
}

// ListComments provides a mock function for the type ICommentService
func (_mock *ICommentService) ListComments(ctx context.Context, in dto.CommentListInput) (dto.CommentListResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 dto.CommentListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CommentListInput) (dto.CommentListResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CommentListInput) dto.CommentListResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.CommentListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CommentListInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ICommentService_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type ICommentService_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.CommentListInput
func (_e *ICommentService_Expecter) ListComments(ctx interface{}, in interface{}) *ICommentService_ListComments_Call {
	return &ICommentService_ListComments_Call{Call: _e.mock.On("ListComments", ctx, in)}
}

func (_c *ICommentService_ListComments_Call) Run(run func(ctx context.Context, in dto.CommentListInput)) *ICommentService_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CommentListInput
		if args[1] != nil {
			arg1 = args[1].(dto.CommentListInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ICommentService_ListComments_Call) Return(commentListResult dto.CommentListResult, err error) *ICommentService_ListComments_Call {
	_c.Call.Return(commentListResult, err)
	return _c
}

func (_c *ICommentService_ListComments_Call) RunAndReturn(run func(ctx context.Context, in dto.CommentListInput) (dto.CommentListResult, error)) *ICommentService_ListComments_Call {
	_c.Call.Return(run)
	return _c
}
