// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/human9001/teams/internal/application/service/task/input"
	"github.com/human9001/teams/internal/domain/task/model"
	mock "github.com/stretchr/testify/mock"
)

// NewITaskService creates a new instance of ITaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITaskService {
	mock := &ITaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITaskService is an autogenerated mock type for the ITaskService type
type ITaskService struct {
	mock.Mock
}

type ITaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *ITaskService) EXPECT() *ITaskService_Expecter {
	return &ITaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type ITaskService
func (_mock *ITaskService) CreateTask(ctx context.Context, userId int64, req input.CreateTaskInput) (*model.Task, error) {
	ret := _mock.Called(ctx, userId, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, input.CreateTaskInput) (*model.Task, error)); ok {
		return returnFunc(ctx, userId, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, input.CreateTaskInput) *model.Task); ok {
		r0 = returnFunc(ctx, userId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, input.CreateTaskInput) error); ok {
		r1 = returnFunc(ctx, userId, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type ITaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
//   - req input.CreateTaskInput
func (_e *ITaskService_Expecter) CreateTask(ctx interface{}, userId interface{}, req interface{}) *ITaskService_CreateTask_Call {
	return &ITaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, userId, req)}
}

func (_c *ITaskService_CreateTask_Call) Run(run func(ctx context.Context, userId int64, req input.CreateTaskInput)) *ITaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 input.CreateTaskInput
		if args[2] != nil {
			arg2 = args[2].(input.CreateTaskInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ITaskService_CreateTask_Call) Return(task *model.Task, err error) *ITaskService_CreateTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *ITaskService_CreateTask_Call) RunAndReturn(run func(ctx context.Context, userId int64, req input.CreateTaskInput) (*model.Task, error)) *ITaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type ITaskService
func (_mock *ITaskService) ListTasks(ctx context.Context, in input.ListTasksInput) (input.ListTasksResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 input.ListTasksResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ListTasksInput) (input.ListTasksResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ListTasksInput) input.ListTasksResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(input.ListTasksResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.ListTasksInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITaskService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type ITaskService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ListTasksInput
func (_e *ITaskService_Expecter) ListTasks(ctx interface{}, in interface{}) *ITaskService_ListTasks_Call {
	return &ITaskService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, in)}
}

func (_c *ITaskService_ListTasks_Call) Run(run func(ctx context.Context, in input.ListTasksInput)) *ITaskService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ListTasksInput
		if args[1] != nil {
			arg1 = args[1].(input.ListTasksInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITaskService_ListTasks_Call) Return(listTasksResult input.ListTasksResult, err error) *ITaskService_ListTasks_Call {
	_c.Call.Return(listTasksResult, err)
	return _c
}

func (_c *ITaskService_ListTasks_Call) RunAndReturn(run func(ctx context.Context, in input.ListTasksInput) (input.ListTasksResult, error)) *ITaskService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type ITaskService
func (_mock *ITaskService) UpdateTask(ctx context.Context, in input.UpdateTaskInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.UpdateTaskInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ITaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type ITaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.UpdateTaskInput
func (_e *ITaskService_Expecter) UpdateTask(ctx interface{}, in interface{}) *ITaskService_UpdateTask_Call {
	return &ITaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, in)}
}

func (_c *ITaskService_UpdateTask_Call) Run(run func(ctx context.Context, in input.UpdateTaskInput)) *ITaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.UpdateTaskInput
		if args[1] != nil {
			arg1 = args[1].(input.UpdateTaskInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITaskService_UpdateTask_Call) Return(err error) *ITaskService_UpdateTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ITaskService_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, in input.UpdateTaskInput) error) *ITaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
